---

- name: Customize shell
  lineinfile:
    dest: "{{ item.path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items: "{{ common_shell_customizations }}"
