---
- name: Validate timezone
  command: readlink /etc/localtime
  register: current_timezone
  changed_when: current_timezone.stdout.find("{{ common_timezone }}") == -1
  check_mode: no

- name: Set timezone
  command: timedatectl set-timezone {{ common_timezone }}
  when: current_timezone.stdout.find("{{ common_timezone }}") == -1
