---
- name: start auditd
  service:
    name: auditd
    state: started
    enabled: yes

- name: reload sshd
  service:
    name: sshd
    state: reloaded
    enabled: yes

- name: restart yum-cron
  service:
    name: yum-cron
    state: restarted
    enabled: yes
